steps:
  - id: backend-test
    name: 'gcr.io/cloud-builders/go:debian'
    env: ['GOPATH=/workspace/_gopath', 'GO111MODULE=on']
    entrypoint: 'make'
    args: ['-C', 'backend', 'test']
  - id: backend-lint
    name: 'golangci/golangci-lint'
    entrypoint: 'make'
    args: ['-C', 'backend', 'lint']
  - id: backend-cover
    name: 'gcr.io/cloud-builders/go:debian'
    env: ['GOPATH=/workspace/_gopath', 'GO111MODULE=on']
    entrypoint: 'make'
    args: ['-C', 'backend', 'check-coverage']
  - id: frontend-cover
    name: 'gcr.io/cloud-builders/npm:current'
    entrypoint: 'make'
    args: ['-C', 'frontend', 'check-coverage']
  - id: frontend-lint
    name: 'gcr.io/cloud-builders/npm:current'
    entrypoint: 'make'
    args: ['-C', 'frontend', 'lint']
  - id: frontend-build
    name: 'gcr.io/cloud-builders/npm:current'
    entrypoint: 'make'
    args: ['-C', 'frontend', 'build']
